const AuthTypes = {
  LOGIN_REQUEST: "AUTH_LOGIN_REQUEST",
  LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  LOGIN_FAILED: "AUTH_LOGIN_FAILED",
  SIGNUP_REQUEST: "AUTH_SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "AUTH_SIGNUP_SUCCESS",
  SIGNUP_FAILED: "AUTH_SIGNUP_FAILED",
  LOGOUT: "AUTH_LOGOUT",
  UPDATE_PASSWORD_REQUEST: "AUTH_UPDATE_PASSWORD_REQUEST",
  UPDATE_PASSWORD_SUCCESS: "AUTH_UPDATE_PASSWORD_SUCCESS",
  UPDATE_PASSWORD_FAILED: "AUTH_UPDATE_PASSWORD_FAILED",
};

const ProfileTypes = {
  GET_ACCOUNT_REQUEST: "GET_PROFILE_REQUEST",
  GET_ACCOUNT_SUCCESS: "GET_PROFILE_SUCCESS",
  UPDATE_ACCOUNT_REQUEST: "UPDATE_PROFILE_REQUEST",
  UPDATE_ACCOUNT_SUCCESS: "UPDATE_PROFILE_SUCCESS",
};

// action_types.js

const AgencyTypes = {
  GET_SPECIFIC_AGENCY_REQUEST: "AGENCY_GET_SPECIFIC_AGENCY_REQUEST",
  GET_SPECIFIC_AGENCY_SUCCESS: "AGENCY_GET_SPECIFIC_AGENCY_SUCCESS",
  GET_SPECIFIC_AGENCY_FAILURE: "AGENCY_GET_SPECIFIC_AGENCY_FAILURE",

  GET_ALL_AGENCIES_REQUEST: "AGENCY_GET_ALL_AGENCIES_REQUEST",
  GET_ALL_AGENCIES_SUCCESS: "AGENCY_GET_ALL_AGENCIES_SUCCESS",
  GET_ALL_AGENCIES_FAILURE: "AGENCY_GET_ALL_AGENCIES_FAILURE",
};

export { AuthTypes, ProfileTypes, AgencyTypes };
